name: Sanitize Postman Files

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.postman_collection.json'
      - '**/*.postman_environment.json'

jobs:
  sanitize:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black requests jsonschema

    - name: Run sanitization script
      id: sanitize
      run: |
        python scripts/sanitize_postman.py .
        echo "modified_files<<EOF" >> $GITHUB_OUTPUT
        git status --porcelain | grep -E '\.postman_(collection|environment)\.json$' | awk '{print $2}' >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Commit and push if changes exist
      if: steps.sanitize.outputs.modified_files != ''
      run: |
        git add .
        git commit -m "chore: sanitize Postman files"
        git push

    - name: Create Pull Request Comment
      if: github.event_name == 'pull_request' && steps.sanitize.outputs.modified_files != ''
      uses: actions/github-script@v7
      with:
        script: |
          const modifiedFiles = process.env.MODIFIED_FILES.split('\n').filter(Boolean);
          const comment = `## Postman Files Sanitized 🔧\n\nThe following Postman files were automatically sanitized to remove metadata:\n\n${modifiedFiles.map(file => `- \`${file}\``).join('\n')}\n\nThis sanitization removes internal IDs and other metadata to keep the repository clean.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
      env:
        MODIFIED_FILES: ${{ steps.sanitize.outputs.modified_files }} 